### ISSUE TITLE
（Add New Spore）It is expected that the size on the chain is equal to 0

### ISSUE THREAD

**Issue by Dawn-githup** [sporeprotocol/spore-demo#47]
![image](https://github.com/sporeprotocol/spore-demo/assets/77844990/5969ef1d-0488-404c-93e0-7ee6b66dab08)

**Comment by ShookLyngs** [comment]
Hi, Dawn. Personally, I consider this as a "feature" because "0 CKB" serves as an indication when the target Spore/Cluster cannot be created on-chain due to errors or any other reason. If you don't like the idea, may I ask how would you like it to display when there's an error or something for the transaction?

**Comment by Dawn-githup** [comment]
> Hi, Dawn. Personally, I consider this as a "feature" because "0 CKB" serves as an indication when the target Spore/Cluster cannot be created on-chain due to errors or any other reason. If you don't like the idea, may I ask how would you like the section to display stuff when there's an error or something for the transaction?

I think "Estimated On-chain Size" is just an estimated size and has nothing to do with other errors. It still displays the estimated size and should not be displayed as zero.

**Comment by Dawn-githup** [comment]
<img width="756" alt="image" src="https://github.com/sporeprotocol/spore-demo/assets/77844990/ecae5158-7809-40bb-a4cf-9b4e7c7d3fd3">

**Comment by ShookLyngs** [comment]
> I think "Estimated On-chain Size" is just an estimated size and has nothing to do with other errors. It still displays the estimated size and should not be displayed as zero.

Okay, I see what you mean there. 

But here's the problem: the estimated on-chain size is not simply calculated from the size of the file. It is actually the exact size of the spore output cell from the spore creation transaction, which is generated from the `createSpore` API. 

Therefore, when the createSpore fails with an error, the estimation also fails.

**Comment by Dawn-githup** [comment]
> > I think "Estimated On-chain Size" is just an estimated size and has nothing to do with other errors. It still displays the estimated size and should not be displayed as zero.
> 
> Okay, I see what you mean there.
> 
> But here's the problem: the estimated on-chain size is not simply calculated from the size of the file. It is actually the exact size of the spore output cell from the spore creation transaction, which is generated from the `createSpore` API.
> 
> Therefore, when the createSpore fails with an error, the estimation also fails.

Okay, I understand, when an error occurs, it can only display like this
