### ISSUE TITLE
Issues related to the v2 version of spore-demo

### ISSUE THREAD

**Issue by Dawn-githup** [sporeprotocol/spore-demo#54]
1. Unable to query v1 cluster
2. Clusters created in v2 will not be displayed without spore.
3. The demo program is easy to crash.

**Comment by Dawn-githup** [comment]
> 1. Unable to query v1 cluster
> 2. Clusters created in v2 will not be displayed without spore.
https://github.com/sporeprotocol/spore-graphql/blob/master/src/resolvers/cluster.ts#L73C20-L73C20

**Comment by Dawn-githup** [comment]
# question category

### spore-demo（Both v1/v2 have problems）
### High
- https://github.com/sporeprotocol/spore-demo/issues/50
- https://github.com/sporeprotocol/spore-demo/issues/42
- https://github.com/sporeprotocol/spore-demo/issues/55
### Medium
- https://github.com/sporeprotocol/spore-demo/issues/47
- https://github.com/sporeprotocol/spore-demo/issues/44
- https://github.com/sporeprotocol/spore-demo/issues/40
### Low
- https://github.com/sporeprotocol/spore-demo/issues/37
- https://github.com/sporeprotocol/spore-demo/issues/39
- https://github.com/sporeprotocol/spore-demo/issues/45
- https://github.com/sporeprotocol/spore-demo/issues/46
- https://github.com/sporeprotocol/spore-demo/issues/48
- https://github.com/sporeprotocol/spore-demo/issues/49

### spore-graphql （v2）
- Unable to query v1 cluster
- Clusters created in v2 will not be displayed without spore.
 I don’t know why I write it like this🤔
https://github.com/sporeprotocol/spore-graphql/blob/master/src/resolvers/cluster.ts#L73C20-L73C20
- The demo program is easy to crash.

**Comment by Dawn-githup** [comment]
issue 3
```
useCapacity.ts:6 
        
        
       GET https://spore-demo-git-feat-v2-contracts-only-sporeprotocol.vercel.app/api/capacity/ckt1qrejnmlar3r452tcg57gvq8patctcgy8acync0hxfnyka35ywafvkqgpqalsrjylxnu3xm0mmgedd5709xv42kdaqqfxkd2l 500 (Internal Server Error)
queryFn @ useCapacity.ts:6
fetchFn @ query.js:175
run @ retryer.js:83
createRetryer @ retryer.js:116
fetch @ query.js:218
#h @ queryObserver.js:170
fetch @ queryObserver.js:160
refetch @ queryObserver.js:149
onFocus @ query.js:82
(anonymous) @ queryCache.js:82
(anonymous) @ queryCache.js:81
batch @ notifyManager.js:16
onFocus @ queryCache.js:80
(anonymous) @ queryClient.js:39
(anonymous) @ focusManager.js:52
onFocus @ focusManager.js:51
(anonymous) @ focusManager.js:39
listener @ focusManager.js:12
Show 17 more frames
Show less
react-dom.production.min.js:189 Error: invalid type: <!DOCTYPE html><html><head><meta charSet="utf-8"/><meta name="viewport" content="minimum-scale=1, initial-scale=1, width=device-width"/><link rel="icon" href="/images/favicon.png"/><meta name="robots" content="index,follow"/><meta name="description" content="A Spore Protocol Demo, based on Next.js + React + Spore SDK."/><meta name="theme-color" content="#FCEB71"/><meta name="twitter:card" content="summary_large_image"/><meta property="og:title" content="Spore Demo"/><meta property="og:description" content="A Spore Protocol Demo, based on Next.js + React + Spore SDK."/><meta property="og:url" content="https://spore-demo.vercel.app"/><meta property="og:type" content="website"/><meta property="og:image" content="/images/og.png"/><meta property="og:image:alt" content="Spore Demo"/><meta property="og:image:type" content="image/png"/><meta property="og:image:width" content="400"/><meta property="og:image:height" content="210"/><meta property="og:locale" content="en"/><meta property="og:site_name" content="Spore Demo"/><title>500: Internal Server Error</title><meta name="next-head-count" content="19"/><link rel="preload" href="/_next/static/media/916d3686010a8de2-s.p.woff2" as="font" type="font/woff2" crossorigin="anonymous" data-next-font="size-adjust"/><link rel="preload" href="/_next/static/media/d869208648ca5469-s.p.woff2" as="font" type="font/woff2" crossorigin="anonymous" data-next-font="size-adjust"/><link rel="preload" href="/_next/static/media/9a881e2ac07d406b-s.p.woff2" as="font" type="font/woff2" crossorigin="anonymous" data-next-font="size-adjust"/><link rel="preload" href="/_next/static/media/bd427f25ac24d036-s.p.woff2" as="font" type="font/woff2" crossorigin="anonymous" data-next-font="size-adjust"/><link rel="preload" href="/_next/static/media/77c9aa6c7112bab0-s.p.woff2" as="font" type="font/woff2" crossorigin="anonymous" data-next-font="size-adjust"/><link rel="preload" href="/_next/static/media/3f4c661fff533b70-s.p.woff2" as="font" type="font/woff2" crossorigin="anonymous" data-next-font="size-adjust"/><link rel="preload" href="/_next/static/css/40c3a916bb35594f.css" as="style" crossorigin=""/><link rel="stylesheet" href="/_next/static/css/40c3a916bb35594f.css" crossorigin="" data-n-g=""/><noscript data-n-css=""></noscript><script defer="" crossorigin="" nomodule="" src="/_next/static/chunks/polyfills-c67a75d1b6f99dc8.js"></script><script src="/_next/static/chunks/webpack-bc54197106ccb121.js" defer="" crossorigin=""></script><script src="/_next/static/chunks/framework-8d53caddf64bc46b.js" defer="" crossorigin=""></script><script src="/_next/static/chunks/main-15ca5ac871b22698.js" defer="" crossorigin=""></script><script src="/_next/static/chunks/pages/_app-2b7e01bf98408d64.js" defer="" crossorigin=""></script><script src="/_next/static/chunks/pages/_error-d71c6be513d61745.js" defer="" crossorigin=""></script><script src="/_next/static/uFUk32rASwaLkAzAKsdQZ/_buildManifest.js" defer="" crossorigin=""></script><script src="/_next/static/uFUk32rASwaLkAzAKsdQZ/_ssgManifest.js" defer="" crossorigin=""></script><style data-emotion="mantine "></style></head><body><div id="__next"><style data-emotion="css-global 1w883ez">html{font-family:sans-serif;line-height:1.15;-webkit-text-size-adjust:100%;-moz-text-size-adjust:100%;-ms-text-size-adjust:100%;text-size-adjust:100%;}body{margin:0;}article,aside,footer,header,nav,section,figcaption,figure,main{display:block;}h1{font-size:2em;}hr{box-sizing:content-box;height:0;overflow:visible;}pre{font-family:monospace,monospace;font-size:1em;}a{background:transparent;text-decoration-skip:objects;}a:active,a:hover{outline-width:0;}abbr[title]{border-bottom:none;-webkit-text-decoration:underline;text-decoration:underline;}b,strong{font-weight:bolder;}code,kbp,samp{font-family:monospace,monospace;font-size:1em;}dfn{font-style:italic;}mark{background-color:#ff0;color:#000;}small{font-size:80%;}sub,sup{font-size:75%;line-height:0;position:relative;vertical-align:baseline;}sup{top:-0.5em;}sub{bottom:-0.25em;}audio,video{display:inline-block;}audio:not([controls]){display:none;height:0;}img{border-style:none;vertical-align:middle;}svg:not(:root){overflow:hidden;}button,input,optgroup,select,textarea{font-family:sans-serif;font-size:100%;line-height:1.15;margin:0;}button,input{overflow:visible;}button,select{text-transform:none;}button,[type=reset],[type=submit]{-webkit-appearance:button;}button::-moz-focus-inner,[type=button]::-moz-focus-inner,[type=reset]::-moz-focus-inner,[type=submit]::-moz-focus-inner{border-style:none;padding:0;}button:-moz-focusring,[type=button]:-moz-focusring,[type=reset]:-moz-focusring,[type=submit]:-moz-focusring{outline:0.0625rem dotted ButtonText;}legend{box-sizing:border-box;color:inherit;display:table;max-width:100%;padding:0;white-space:normal;}progress{display:inline-block;vertical-align:baseline;}textarea{overflow:auto;}[type=checkbox],[type=radio]{box-sizing:border-box;padding:0;}[type=number]::-webkit-inner-spin-button,[type=number]::-webkit-outer-spin-button{height:auto;}[type=search]{-webkit-appearance:none;-moz-appearance:none;-ms-appearance:none;appearance:none;}[type=search]::-webkit-search-cancel-button,[type=search]::-webkit-search-decoration{-webkit-appearance:none;-moz-appearance:none;-ms-appearance:none;appearance:none;}::-webkit-file-upload-button{-webkit-appearance:button;-moz-appearance:button;-ms-appearance:button;appearance:button;font:inherit;}details,menu{display:block;}summary{display:-webkit-box;display:-webkit-list-item;display:-ms-list-itembox;display:list-item;}canvas{display:inline-block;}template{display:none;}</style><style data-emotion="css-global oh2gs5">*,*::before,*::after{box-sizing:border-box;}html{-webkit-print-color-scheme:light;color-scheme:light;}body{font-family:'__Kulim_Park_6f5169','__Kulim_Park_Fallback_6f5169',sans-serif;background-color:#fff;color:#000;line-height:1.55;font-size:16px;-webkit-font-smoothing:antialiased;-moz-osx-font-smoothing:grayscale;}</style><div style="font-family:system-ui,&quot;Segoe UI&quot;,Roboto,Helvetica,Arial,sans-serif,&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot;;height:100vh;text-align:center;display:flex;flex-direction:column;align-items:center;justify-content:center"><div style="line-height:48px"><style>body{color:#000;background:#fff;margin:0}.next-error-h1{border-right:1px solid rgba(0,0,0,.3)}@media (prefers-color-scheme:dark){body{color:#fff;background:#000}.next-error-h1{border-right:1px solid rgba(255,255,255,.3)}}</style><h1 class="next-error-h1" style="display:inline-block;margin:0 20px 0 0;padding-right:23px;font-size:24px;font-weight:500;vertical-align:top">500</h1><div style="display:inline-block"><h2 style="font-size:14px;font-weight:400;line-height:28px">Internal Server Error<!-- -->.</h2></div></div></div></div><script id="__NEXT_DATA__" type="application/json" crossorigin="">{"props":{"pageProps":{"statusCode":500}},"page":"/_error","query":{},"buildId":"uFUk32rASwaLkAzAKsdQZ","nextExport":true,"isFallback":false,"gip":true,"scriptLoader":[]}</script></body></html> can't be converted into BI
    at BI.from (index.js:127:1)
    at my.tsx:108:26
    at Object.Ci [as useMemo] (react-dom.production.min.js:179:117)
    at t.useMemo (react.production.min.js:25:191)
    at MySpacePage (my.tsx:106:19)
    at Xh (react-dom.production.min.js:167:135)
    at dj (react-dom.production.min.js:197:256)
    at x (react-dom.production.min.js:292:18)
    at Vk (react-dom.production.min.js:280:383)
    at react-dom.production.min.js:280:319
    ```

**Comment by Dawn-githup** [comment]
> issue 3
> 
> ```
> useCapacity.ts:6 
>         
>         
>        GET https://spore-demo-git-feat-v2-contracts-only-sporeprotocol.vercel.app/api/capacity/ckt1qrejnmlar3r452tcg57gvq8patctcgy8acync0hxfnyka35ywafvkqgpqalsrjylxnu3xm0mmgedd5709xv42kdaqqfxkd2l 500 (Internal Server Error)
> queryFn @ useCapacity.ts:6
> fetchFn @ query.js:175
> run @ retryer.js:83
> createRetryer @ retryer.js:116
> fetch @ query.js:218
> #h @ queryObserver.js:170
> fetch @ queryObserver.js:160
> refetch @ queryObserver.js:149
> onFocus @ query.js:82
> (anonymous) @ queryCache.js:82
> (anonymous) @ queryCache.js:81
> batch @ notifyManager.js:16
> onFocus @ queryCache.js:80
> (anonymous) @ queryClient.js:39
> (anonymous) @ focusManager.js:52
> onFocus @ focusManager.js:51
> (anonymous) @ focusManager.js:39
> listener @ focusManager.js:12
> Show 17 more frames
> Show less
> react-dom.production.min.js:189 Error: invalid type: <!DOCTYPE html><html><head><meta charSet="utf-8"/><meta name="viewport" content="minimum-scale=1, initial-scale=1, width=device-width"/><link rel="icon" href="/images/favicon.png"/><meta name="robots" content="index,follow"/><meta name="description" content="A Spore Protocol Demo, based on Next.js + React + Spore SDK."/><meta name="theme-color" content="#FCEB71"/><meta name="twitter:card" content="summary_large_image"/><meta property="og:title" content="Spore Demo"/><meta property="og:description" content="A Spore Protocol Demo, based on Next.js + React + Spore SDK."/><meta property="og:url" content="https://spore-demo.vercel.app"/><meta property="og:type" content="website"/><meta property="og:image" content="/images/og.png"/><meta property="og:image:alt" content="Spore Demo"/><meta property="og:image:type" content="image/png"/><meta property="og:image:width" content="400"/><meta property="og:image:height" content="210"/><meta property="og:locale" content="en"/><meta property="og:site_name" content="Spore Demo"/><title>500: Internal Server Error</title><meta name="next-head-count" content="19"/><link rel="preload" href="/_next/static/media/916d3686010a8de2-s.p.woff2" as="font" type="font/woff2" crossorigin="anonymous" data-next-font="size-adjust"/><link rel="preload" href="/_next/static/media/d869208648ca5469-s.p.woff2" as="font" type="font/woff2" crossorigin="anonymous" data-next-font="size-adjust"/><link rel="preload" href="/_next/static/media/9a881e2ac07d406b-s.p.woff2" as="font" type="font/woff2" crossorigin="anonymous" data-next-font="size-adjust"/><link rel="preload" href="/_next/static/media/bd427f25ac24d036-s.p.woff2" as="font" type="font/woff2" crossorigin="anonymous" data-next-font="size-adjust"/><link rel="preload" href="/_next/static/media/77c9aa6c7112bab0-s.p.woff2" as="font" type="font/woff2" crossorigin="anonymous" data-next-font="size-adjust"/><link rel="preload" href="/_next/static/media/3f4c661fff533b70-s.p.woff2" as="font" type="font/woff2" crossorigin="anonymous" data-next-font="size-adjust"/><link rel="preload" href="/_next/static/css/40c3a916bb35594f.css" as="style" crossorigin=""/><link rel="stylesheet" href="/_next/static/css/40c3a916bb35594f.css" crossorigin="" data-n-g=""/><noscript data-n-css=""></noscript><script defer="" crossorigin="" nomodule="" src="/_next/static/chunks/polyfills-c67a75d1b6f99dc8.js"></script><script src="/_next/static/chunks/webpack-bc54197106ccb121.js" defer="" crossorigin=""></script><script src="/_next/static/chunks/framework-8d53caddf64bc46b.js" defer="" crossorigin=""></script><script src="/_next/static/chunks/main-15ca5ac871b22698.js" defer="" crossorigin=""></script><script src="/_next/static/chunks/pages/_app-2b7e01bf98408d64.js" defer="" crossorigin=""></script><script src="/_next/static/chunks/pages/_error-d71c6be513d61745.js" defer="" crossorigin=""></script><script src="/_next/static/uFUk32rASwaLkAzAKsdQZ/_buildManifest.js" defer="" crossorigin=""></script><script src="/_next/static/uFUk32rASwaLkAzAKsdQZ/_ssgManifest.js" defer="" crossorigin=""></script><style data-emotion="mantine "></style></head><body><div id="__next"><style data-emotion="css-global 1w883ez">html{font-family:sans-serif;line-height:1.15;-webkit-text-size-adjust:100%;-moz-text-size-adjust:100%;-ms-text-size-adjust:100%;text-size-adjust:100%;}body{margin:0;}article,aside,footer,header,nav,section,figcaption,figure,main{display:block;}h1{font-size:2em;}hr{box-sizing:content-box;height:0;overflow:visible;}pre{font-family:monospace,monospace;font-size:1em;}a{background:transparent;text-decoration-skip:objects;}a:active,a:hover{outline-width:0;}abbr[title]{border-bottom:none;-webkit-text-decoration:underline;text-decoration:underline;}b,strong{font-weight:bolder;}code,kbp,samp{font-family:monospace,monospace;font-size:1em;}dfn{font-style:italic;}mark{background-color:#ff0;color:#000;}small{font-size:80%;}sub,sup{font-size:75%;line-height:0;position:relative;vertical-align:baseline;}sup{top:-0.5em;}sub{bottom:-0.25em;}audio,video{display:inline-block;}audio:not([controls]){display:none;height:0;}img{border-style:none;vertical-align:middle;}svg:not(:root){overflow:hidden;}button,input,optgroup,select,textarea{font-family:sans-serif;font-size:100%;line-height:1.15;margin:0;}button,input{overflow:visible;}button,select{text-transform:none;}button,[type=reset],[type=submit]{-webkit-appearance:button;}button::-moz-focus-inner,[type=button]::-moz-focus-inner,[type=reset]::-moz-focus-inner,[type=submit]::-moz-focus-inner{border-style:none;padding:0;}button:-moz-focusring,[type=button]:-moz-focusring,[type=reset]:-moz-focusring,[type=submit]:-moz-focusring{outline:0.0625rem dotted ButtonText;}legend{box-sizing:border-box;color:inherit;display:table;max-width:100%;padding:0;white-space:normal;}progress{display:inline-block;vertical-align:baseline;}textarea{overflow:auto;}[type=checkbox],[type=radio]{box-sizing:border-box;padding:0;}[type=number]::-webkit-inner-spin-button,[type=number]::-webkit-outer-spin-button{height:auto;}[type=search]{-webkit-appearance:none;-moz-appearance:none;-ms-appearance:none;appearance:none;}[type=search]::-webkit-search-cancel-button,[type=search]::-webkit-search-decoration{-webkit-appearance:none;-moz-appearance:none;-ms-appearance:none;appearance:none;}::-webkit-file-upload-button{-webkit-appearance:button;-moz-appearance:button;-ms-appearance:button;appearance:button;font:inherit;}details,menu{display:block;}summary{display:-webkit-box;display:-webkit-list-item;display:-ms-list-itembox;display:list-item;}canvas{display:inline-block;}template{display:none;}</style><style data-emotion="css-global oh2gs5">*,*::before,*::after{box-sizing:border-box;}html{-webkit-print-color-scheme:light;color-scheme:light;}body{font-family:'__Kulim_Park_6f5169','__Kulim_Park_Fallback_6f5169',sans-serif;background-color:#fff;color:#000;line-height:1.55;font-size:16px;-webkit-font-smoothing:antialiased;-moz-osx-font-smoothing:grayscale;}</style><div style="font-family:system-ui,&quot;Segoe UI&quot;,Roboto,Helvetica,Arial,sans-serif,&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot;;height:100vh;text-align:center;display:flex;flex-direction:column;align-items:center;justify-content:center"><div style="line-height:48px"><style>body{color:#000;background:#fff;margin:0}.next-error-h1{border-right:1px solid rgba(0,0,0,.3)}@media (prefers-color-scheme:dark){body{color:#fff;background:#000}.next-error-h1{border-right:1px solid rgba(255,255,255,.3)}}</style><h1 class="next-error-h1" style="display:inline-block;margin:0 20px 0 0;padding-right:23px;font-size:24px;font-weight:500;vertical-align:top">500</h1><div style="display:inline-block"><h2 style="font-size:14px;font-weight:400;line-height:28px">Internal Server Error.</h2></div></div></div></div><script id="__NEXT_DATA__" type="application/json" crossorigin="">{"props":{"pageProps":{"statusCode":500}},"page":"/_error","query":{},"buildId":"uFUk32rASwaLkAzAKsdQZ","nextExport":true,"isFallback":false,"gip":true,"scriptLoader":[]}</script></body></html> can't be converted into BI
>     at BI.from (index.js:127:1)
>     at my.tsx:108:26
>     at Object.Ci [as useMemo] (react-dom.production.min.js:179:117)
>     at t.useMemo (react.production.min.js:25:191)
>     at MySpacePage (my.tsx:106:19)
>     at Xh (react-dom.production.min.js:167:135)
>     at dj (react-dom.production.min.js:197:256)
>     at x (react-dom.production.min.js:292:18)
>     at Vk (react-dom.production.min.js:280:383)
>     at react-dom.production.min.js:280:319
>     ```
> ```

### Operational steps:
1.Create spore/cluster
2.After signing, wait for a while and the probability will appear.

**Comment by ashuralyk** [comment]
```
spore-graphql （v2）

Unable to query v1 cluster
Clusters created in v2 will not be displayed without spore.
I don’t know why I write it like this🤔
https://github.com/sporeprotocol/spore-graphql/blob/master/src/resolvers/cluster.ts#L73C20-L73C20
The demo program is easy to crash.
```

these bugs from spore-graphql are still there?

**Comment by Dawn-githup** [comment]
https://github.com/sporeprotocol/spore-demo/issues/65
